import { NgModule } from '@angular/core';

import {
    MatSidenavModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatTooltipModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatSortModule,
    MatTableModule,
    MatPaginatorModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatToolbarModule,
    MatMenuModule,
    MatCardModule,
    MatGridListModule,
    MatCheckboxModule,
    MatSliderModule,
    MatDividerModule,
    MatSnackBarModule,
    MatBadgeModule,
    MatFormFieldModule,
    MatExpansionModule,
    MatRadioModule
} from '@angular/material';

@NgModule({
    imports: [
        MatSidenavModule,
        MatInputModule,
        MatIconModule,
        MatButtonModule,
        MatTooltipModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatSortModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatToolbarModule,
        MatMenuModule,
        MatCardModule,
        MatGridListModule,
        MatCheckboxModule,
        MatSliderModule,
        MatDividerModule,
        MatSnackBarModule,
        MatBadgeModule,
        MatFormFieldModule,
        MatExpansionModule,
        MatRadioModule
    ],
    exports: [
        MatMenuModule,
        MatCardModule,
        MatBadgeModule,
        MatSidenavModule,
        MatInputModule,
        MatIconModule,
        MatButtonModule,
        MatTooltipModule,
        MatChipsModule,
        MatProgressSpinnerModule,
        MatSortModule,
        MatTableModule,
        MatPaginatorModule,
        MatSelectModule,
        MatSlideToggleModule,
        MatDialogModule,
        MatFormFieldModule,
        MatToolbarModule,
        MatGridListModule,
        MatCheckboxModule,
        MatSliderModule,
        MatDividerModule,
        MatSnackBarModule,
        MatExpansionModule,
        MatRadioModule
    ],
    declarations: [],
    providers: [],
})
export class MaterialModule { }
